### ISSUE TITLE
The React props don't update based on the parent Blaze template data context

### ISSUE THREAD

**Issue by clayne11** [dferber90/meteor-react-create-blaze-template#1]
You need to add an autorun to re-render the template.

``` javascript
  template.onRendered(function() {
    var self = this;

    this.container = renderInPlaceOfNode(
      // Equivalent to <Component {...this.data} />:
      React.createElement(Component, this.data || {}),
      this.find("span")
    );

    self.autorun(function() {
      React.render(
        React.createElement(Component, Template.currentData() || {}), 
        self.container);
    });
  });
```

**Comment by dferber90** [comment]
I've missed the notification for issue, sorry about that. Thanks for pointing the issue out. With this approach there seems to be a problem in case the element rendered to has siblings.

MDG is working on an official way to include React and one of those packages offers the same functionality as this one (and more). I'm also not using this package currently and will eventually deprecate it once MDG's solution is out.

**Comment by clayne11** [comment]
You're right, it doesn't work if there are siblings, but it's simple to wrap the React component in a div to fix this issue.

``` HTML
<div>
  {{>MyReactComponent data}}
</div>
```

In my opinion it's far more important for the component to be Reactive than to have siblings. In any case, I've taken your code and adapted it for my needs. When the official method comes out I will migrate to that as well.
